# Generated by Django 3.0.3 on 2020-07-10 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='contentPreview',
            new_name='content_preview',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='hasChild',
            new_name='has_child',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='parentCategoryId',
            new_name='parent_category_id',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='userType',
            new_name='user_type',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='profileImgPath',
            new_name='profile_img_path',
        ),
    ]
