# Generated by Django 3.0.3 on 2020-07-10 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200710_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='isActive',
            new_name='is_active',
        ),
    ]
