# Generated by Django 3.0.3 on 2020-07-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200710_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='has_child',
            field=models.CharField(default='N', max_length=2, null=None),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
